### ISSUE TITLE
RAPL backend not working for Linux 5.10+

### ISSUE THREAD

**Issue by TomTheBear** [Helmholtz-AI-Energy/perun#49]
With the Linux kernel 5.10, the permissions of the `energy_uj` file were changed to be readable only as root but `perun` is commonly used as user.

Reference: https://github.com/powercap/powercap/issues/7

**Comment by JuanPedroGHM** [comment]
Thanks for the issue. I'm well aware that it is not accessible by default, and that and admin might be needed to provide read access to users.  Sadly, as far as I know, this is the only reliable way to get accurate energy readings out of an Intel CPU, and it is used by most of the energy monitoring applications for Linux. 

If you have any alternative, please let me know :)

**Comment by TomTheBear** [comment]
I opened the issue more for documentation purposes. The restricted access to `energy_uj` seems not to be documented for this perun.

The alternatives I currently recall are:
- use `perf_event_open` if `/proc/sys/kernel/perf_event_paranoid <= 0`. Maybe POSIX capability `CAP_PERFMON` works as well.
- include a `systemd` service file or `udev` rule in the repository with documentation for their installation
- Fallback to IPMI or Redfish for node-level energy/power readings
- [msr-safe](https://github.com/LLNL/msr-safe) kernel module and [Variorum](https://github.com/LLNL/variorum)
- [LIKWID](https://github.com/RRZE-HPC/likwid) (I mention it as last because I am the developer. Can be used with [msr-safe](https://github.com/LLNL/msr-safe) as well)

**Comment by JuanPedroGHM** [comment]
Those are all good alternatives, but I think they don't solve the problem of needing an admin. But you are right that this should be better documented (currently working on sphinx documentation on [another branch](https://github.com/Helmholtz-AI-Energy/perun/tree/docs/sphinx-docs)).

It is definitely in my goals to expand and add more alternatives to obtain the data, and it makes sense to integrate with a tool like LIKWID in case it is already in the system.

**Comment by TomTheBear** [comment]
I would first check whether `perf_event` can be used before trying any other tool. Almost all Linux system provides it (some cloud vendors patch it out). Other tools like PAPI or LIKWID are often not loaded by default (e.g. module system). If ` msr_safe` is available, you can access the RAPL registers though this interface as a user if admins added the registers once to the allowed register list. The default lists contain the RAPL registers.

Close the issue when you don't need it anymore as reminder.
