### ISSUE TITLE
benchmark example might be helpful

### ISSUE THREAD

**Issue by psteinb** [Helmholtz-AI-Energy/perun#62]
Thanks for this great tool @JuanPedroGHM et al!

For people to get started, it might be a good idea to have a small (ML) example in stock with the repo. Something like classification of MNIST or similar with pytorch. What do you think?

**Comment by JuanPedroGHM** [comment]
It's definitely a good idea. I've created a pull request with a starting point, that I will expand on in the next days. Give it a look if you have the time, and let me know if it is similar to what you had in mind.
