### ISSUE TITLE
Cannot get the same type of results of torch_mnist

### ISSUE THREAD

**Issue by aweissen1** [Helmholtz-AI-Energy/perun#87]
I was executing the example on a system without a GPU and I receive the following results:

PERUN REPORT

App name: torch_mnist
First run: 2023-10-23T17:01:42.007616
Last run: 2023-10-23T17:23:35.895179

RUN ID: 2023-10-23T17:23:35.895179

|   Round # | Host      | RUNTIME   | CPU_UTIL   | MEM_UTIL   |
|----------:|:----------|:----------|:-----------|:-----------|
|         0 | l3dss2210 | 141.391 s | 62.805 %   | 0.128 %    |
|         0 | All       | 141.391 s | 62.805 %   | 0.128 %    |

Monitored Functions

|   Round # | Function    |   Avg Calls / Rank | Avg Runtime     | Avg Power     | Avg CPU Util   | Avg GPU Mem Util   |
|----------:|:------------|-------------------:|:----------------|:--------------|:---------------|:-------------------|
|         0 | train       |                  1 | 140.292±0.000 s | 0.000±0.000 W | 63.143±0.000 % | 0.000±0.000 %      |
|         0 | train_epoch |                  5 | 25.732±0.685 s  | 0.000±0.000 W | 63.741±1.229 % | 0.000±0.000 %      |
|         0 | test        |                  5 | 2.325±0.062 s   | 0.000±0.000 W | 54.353±1.090 % | 0.000±0.000 %      |

The application has run been run 2 times.

How can I get the energy consumption such as "CPU_POWER" and "DRAM_POWER"?
Do I need to configure the system at the beginning?

Thanks and BR
Axel

**Comment by JuanPedroGHM** [comment]
Hi Alex,

Thanks for submitting an issue. What hardware are you using? Perun works best on Linux machines using Intel CPUs, with some AMD CPUs being supported. If this matches your setup, it could be that you don't have access to the required files in the file system. You need to make sure the files in "/sys/class/powercap/" are readable to you.

You can get more information on the powercap interface [here](https://www.kernel.org/doc/html/latest/power/powercap/powercap.html)
